### ISSUE TITLE
朋友圈部分内容不显示

### ISSUE THREAD

**Issue by MacLeek** [AlayshChen/WeChatPlugin#2]
具体是：动态页小视频不显示，他人主页只显示图片，自己的主页正常。

**Comment by AlayshChen** [comment]
谢谢 我看看

**Comment by moxiaobei2** [comment]
怎么装啊？

**Comment by Jackylee1992** [comment]
点击图片崩溃。Failed to connect (loadingViewContainer) outlet from (MMPreviewPanel) to (NSView): missing setter or instance variable

**Comment by 627969687** [comment]
/Users/kuyou1/Library/Developer/Xcode/DerivedData/WeChatPlugin-aloagybvzomzfxcucbzrujfvncrm/Build/Intermediates/WeChatPlugin.build/Debug/WeChat.build/Script-803DAFC01E853D3F00ADCC86.sh: line 13: insert_dylib: command not found

**Comment by 627969687** [comment]
/Users/kuyou1/Library/Developer/Xcode/DerivedData/WeChatPlugin-aloagybvzomzfxcucbzrujfvncrm/Build/Intermediates/WeChatPlugin.build/Debug/WeChat.build/Script-803DAFC01E853D3F00ADCC86.sh: line 13: insert_dylib: command not found

运行报这个错误，如何解决

**Comment by Jackylee1992** [comment]
下载insert_dylib并运行，将生成的文件放入/use/bin目录下
发自网易邮箱大师
在2017年04月06日 19:06，Jason 写道： /Users/kuyou1/Library/Developer/Xcode/DerivedData/WeChatPlugin-aloagybvzomzfxcucbzrujfvncrm/Build/Intermediates/WeChatPlugin.build/Debug/WeChat.build/Script-803DAFC01E853D3F00ADCC86.sh: line 13: insert_dylib: command not found
运行报这个错误，如何解决

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/AlayshChen/WeChatPlugin","title":"AlayshChen/WeChatPlugin","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/AlayshChen/WeChatPlugin"}},"updates":{"snippets":[{"icon":"PERSON","message":"@627969687 in #2: /Users/kuyou1/Library/Developer/Xcode/DerivedData/WeChatPlugin-aloagybvzomzfxcucbzrujfvncrm/Build/Intermediates/WeChatPlugin.build/Debug/WeChat.build/Script-803DAFC01E853D3F00ADCC86.sh: line 13: insert_dylib: command not found\r\n\r\n运行报这个错误，如何解决"}],"action":{"name":"View Issue","url":"https://github.com/AlayshChen/WeChatPlugin/issues/2#issuecomment-292140901"}}}

**Comment by MacLeek** [comment]
今天有时间试了试，发现只要模拟成ios版本的就都正常了😂

**Comment by AlayshChen** [comment]
赞

**Comment by ptdongguan** [comment]
我怎么朋友圈还是空白？recall等功能倒是有了。
